#!/usr/bin/env node
// Netlify build step for the dashboard (run from Web_Dashboard/, see netlify.toml).
//
// 1. Writes assets/env.js from environment variables:
//      SUPABASE_URL, SUPABASE_ANON_KEY (or SUPABASE_KEY), API_ADAPTER_MODE, API_BASE_URL
// 2. Writes _headers with a strict Content-Security-Policy and security headers,
//    allowing connections only to the configured Supabase project.
//
// Refuses to build with a secret (service_role) key, because env.js is public.
// Outside Netlify it only prints what it would write, unless OUTPUT_DIR is set.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

function fail(message) {
  console.error(`netlify-build: ${message}`);
  process.exit(1);
}

function origin(value, label) {
  try {
    const url = new URL(value);
    const local = ['localhost', '127.0.0.1'].includes(url.hostname);
    if (url.protocol !== 'https:' && !(url.protocol === 'http:' && local)) {
      fail(`${label} must use https:// (got ${url.protocol}//${url.host}).`);
    }
    return url.origin;
  } catch (_) {
    fail(`${label} is not a valid URL: ${value}`);
    return '';
  }
}

function isSecretKey(key) {
  if (key.startsWith('sb_secret_')) return true;
  const parts = key.split('.');
  if (parts.length !== 3) return false;
  try {
    return JSON.parse(Buffer.from(parts[1], 'base64url').toString('utf8')).role === 'service_role';
  } catch (_) {
    return false;
  }
}

const supabaseUrl = (process.env.SUPABASE_URL || '').trim().replace(/\/+$/, '');
const supabaseKey = (process.env.SUPABASE_ANON_KEY || process.env.SUPABASE_KEY || '').trim();
const adapterMode = (process.env.API_ADAPTER_MODE || 'local').trim().toLowerCase() === 'remote' ? 'remote' : 'local';
const apiBaseUrl = (process.env.API_BASE_URL || '').trim().replace(/\/+$/, '');

if (supabaseKey && isSecretKey(supabaseKey)) {
  fail('SUPABASE_ANON_KEY is a secret (service_role) key. Use the anon or publishable key: env.js is public.');
}
if (!supabaseUrl || !supabaseKey) {
  console.warn('netlify-build: SUPABASE_URL or SUPABASE_ANON_KEY is not set; the dashboard will ask for them in Settings.');
}

const connectSources = ["'self'"];
if (supabaseUrl) {
  const supabaseOrigin = origin(supabaseUrl, 'SUPABASE_URL');
  connectSources.push(supabaseOrigin, supabaseOrigin.replace(/^http/, 'ws'));
} else {
  connectSources.push('https://*.supabase.co', 'wss://*.supabase.co');
}
if (adapterMode === 'remote') {
  if (!apiBaseUrl) fail('API_ADAPTER_MODE is remote but API_BASE_URL is not set.');
  connectSources.push(origin(apiBaseUrl, 'API_BASE_URL'));
}

const env = {
  SUPABASE_URL: supabaseUrl,
  SUPABASE_KEY: supabaseKey,
  API_ADAPTER_MODE: adapterMode,
  API_BASE_URL: adapterMode === 'remote' ? apiBaseUrl : ''
};
const envJs = `// Generated by scripts/netlify-build.mjs at deploy time.\nwindow.__ENV__ = ${JSON.stringify(env, null, 2)};\n`;

const csp = [
  "default-src 'self'",
  "script-src 'self' https://cdn.jsdelivr.net",
  "style-src 'self' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data:",
  `connect-src ${connectSources.join(' ')}`,
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'"
].join('; ');

const headers = `/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=()
  Strict-Transport-Security: max-age=31536000; includeSubDomains

/assets/env.js
  Cache-Control: no-cache
`;

const outputDir = process.env.NETLIFY === 'true' ? process.cwd() : process.env.OUTPUT_DIR;
if (!outputDir) {
  console.log('Not running on Netlify and OUTPUT_DIR is not set, so nothing was written. Would write:\n');
  console.log(`--- assets/env.js ---\n${envJs}\n--- _headers ---\n${headers}`);
  process.exit(0);
}

mkdirSync(join(outputDir, 'assets'), { recursive: true });
writeFileSync(join(outputDir, 'assets', 'env.js'), envJs);
writeFileSync(join(outputDir, '_headers'), headers);
console.log(`netlify-build: wrote assets/env.js and _headers (adapter: ${adapterMode}).`);
